### ISSUE TITLE
How do I get into heaven?

### ISSUE THREAD

**Issue by martyychang** [martyychang/christianity-in-24#22]
The practical question at the end of the day: How does anyone get into heaven? Is it just by claiming Jesus to be humanity's savior? Is through works and deeds?

**Comment by ghost** [comment]
Through faith in Christ alone, by the grace of God alone.

What is faith? Not merely claiming Jesus to be humanity's savior; not merely assenting to facts about him; but taking hold of Christ's work and claiming it for your own salvation.  

Or, as New City Catechism #30 puts it: "Faith in Jesus Christ is acknowledging the truth of everything that God has revealed in his Word, trusting in him, and also receiving and resting on him alone for salvation as he is offered to us in the gospel."

**Comment by martyychang** [comment]
Thanks for the perspective, @rightfromleft and this is one I hear very commonly. However, I think your own statement, "taking hold of Christ's work and claiming it for your own salvation" is more action-oriented and truthful than the quote from New City Catechism.

Perhaps we're simply mincing words here, but the way I read and I see others interpret these statements is that they feel like simply _stating_ a belief that Christ was real and that he died on the cross for us is enough. I believe lip service is far from satisfactory to God, which is why I thought it would be worthwhile to get into specific details and examples.

How can you tell whether someone has faith? Better yet, how can you know that _you_ have faith? I've heard people say that only God knows, but actually I think with just a couple of questions one can get a pretty good idea.

**Comment by ghost** [comment]
"Acknowledging"a particular belief is only the starting point.  Faith also requires the "trusting", "receiving" and "resting."  It's like that story of a tightrope walker who walked across Niagra falls.  He was so good at walking across the tightrope, that he publicized that he'd walk across while carrying a barrel.  As a crowd watched him, he said "who of you think I can walk across while carrying a barrel?" Everyone cheered and exclaimed that they believed that he could do it.  "Alright," he said, "then who of you would go inside the barrel as I carried it?"  No one did.  That's the difference between mere assenting of a fact and placing one's trust as one's whole salvation.

Being able to discern one's salvation while related is not to be conflated with the cause of one's salvation.

**Comment by martyychang** [comment]
👍 for the tightrope walker story, @rightfromleft , I think that's spot on. The story pretty much sums up how I feel about the overwhelming majority of the [70% in America who claim to be Christians][1].

[1]: http://www.pewforum.org/religious-landscape-study/

**Comment by martyychang** [comment]
Resolved by #23 for now. More detailed questions may prompt updates to the content.
